project_name: protoc-gen-connect-es
builds:
  - main: ./cmd/protoc-gen-connect-es
    id: es
    binary: protoc-gen-connect-es
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm64
archives:
  - format_overrides:
      - goos: windows
        format: zip
release:
  mode: append
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  disable: true
